name: Running a test
on:
  push:
    branches: "**"
  
jobs:
  test_workflow:
    name: Test Workflow
    runs-on: ubuntu-latest
    steps:
    - name: Echo
      run: echo test123
    - name: Echo 2
      run: echo test456