name: Running a test
on:
  schedule:
    - cron: '0 12 * * *'
  # branches: "master"
  
jobs:
  test_workflow:
    name: Test Workflow
    runs-on: ubuntu-latest
    steps:
    - name: Echo
      run: echo test987
    - name: Echo 2
      run: echo test654